### ISSUE TITLE
Update starknet and snforge versions

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-contracts#1]
Update starknet to `v2.8.3` and snforge_std to `v0.31.0` 
Update the setup docs on how to use the above version locally And update the contract code with new changes that come with above version.

**Comment by Akshola00** [comment]
Can I work on this issue, @Oshioke-Salaki? I can quickly update the StarkNet and SnForge versions so that other issues can use the updated versions.

**Comment by Yunusabdul38** [comment]
I'd love to work on this issue.
and make sure it meets the requirements

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by Jemiiah** [comment]
I would love to work on this issue plwase may i  be assigned ETA: 24hrs

**Comment by Jemiiah** [comment]
Please can i work on this issue within an ETA : 24 HRS
