### ISSUE TITLE
Create a comprehensive documentation

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-contracts#15]
Create a comprehensive documentation and update the project readMe to include the setup instructions. This should be clear enough for user and developers.

#### Task
1.⁠ ⁠Create a new [Vocs project](https://vocs.dev/docs/) in a directory named book. Add technical documentation for the project that  details out the project architecture.

2.⁠ ⁠Update project readMe to include user guide and setup instructions.

I will be assigning two people to this.

**Comment by Mystic-Nayy** [comment]
@Oshioke-Salaki Can i work on this?

**Comment by Iwueseiter** [comment]
Hi @Oshioke-Salaki can I work on this?

**Comment by binayak9932** [comment]
I'd like to handle this task.I  am new to this repo  and would love to contribute to this project.
