### ISSUE TITLE
Write a function that deploys an NFT for each campaign

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-contracts#2]
Write a private function that deploys a campaign NFT using the following interface,
```
fn _deploy_campaign_nft(
        ref self: ComponentState<TContractState>,
        campaign_id: u256,
        token_giver_nft_class_hash: ClassHash,
) -> ContractAddress
```
Use salt as get_block_timestamp().into() deploy_syscall

**Comment by Immanuelolivia1** [comment]
Can I take care of this issue?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  already  seen all code of this project i think I have good understanding  in this project .   please /assign  this issue .
Thank You

**Comment by ShantelPeters** [comment]
I'd be happy to do this.

**Comment by Iwueseiter** [comment]
Is it okay if I tackle this?

I'm a frontend and smart contract developer. I have a solid background in tailwindCSS, react, nextjs, javascript, typescript, cairo, rust ETC.
