### ISSUE TITLE
Test create_campaign function

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-contracts#3]
Write end to end unit testing for create_campaign function.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by OWK50GA** [comment]
Can I handle this task?
I'm a Cairo developer adept at resting smart contracts.
ETA - 1 day

**Comment by Emmanex01** [comment]
I'd love to give this a go.

**Comment by Birdmannn** [comment]
Can I also be assigned this sir? Any one you have, I'll deliver. I've gone through this repo prior to today

**Comment by GideonBature** [comment]
Could I take on this issue?

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If assigned this issue, I will send my first PR within 72 hrs. 

Thank you!

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  already  seen all code of this project i think I have good understanding  in this project .   please /assign  this issue .
Thank You

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with great experience contributing Cairo projects.
Could I be assigned to this?

**Comment by ShantelPeters** [comment]
May I take care of this?

**Comment by zintarh** [comment]
Let me handle this issue!

nderstand the Function: Identify key behaviors like input validation, business logic, database interaction, and API responses.

Setup Test Environment:

Use Jest for testing.
Use Supertest for simulating HTTP requests.
Set up a mock/test database to avoid affecting production.
Write Tests:

Positive Test: Ensure valid inputs create a campaign and return the correct response (e.g., 200 OK).
Negative Tests: Test invalid inputs (e.g., missing fields, invalid data types) and ensure appropriate error responses (e.g., 400 Bad Request).
Database Validation: Ensure the campaign is correctly created in the database.
Edge Cases: Test duplicate campaigns, invalid states, and service failures (e.g., 500 Internal Server Error).
R

**Comment by emarc99** [comment]
I'd like to handle this task and write the best test and ensure it passes by running `scarb test`. I have scarb 2.8.4 already intalled. eta 3hours. I have done similar task in OD.

**Comment by No-bodyq** [comment]
Can I contribute to this one?

**Comment by mimiprosper** [comment]
I'd love to work on this!  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 2 days.
