### ISSUE TITLE
Restructure Compaign Contract Implementation

### ISSUE THREAD

**Issue by mubarak23** [Token-Giver/token-giver-contracts#34]
Refactor the existing contract implementation base on the following details

- Each Campaign will have a minted NFT 
- Use token giver NFT contract address and campaign token_id to create a dedicated TBA account for each new campaign.
- Dedicated TBA account will be used to received donation for each campaign
- Save token giver NFT contract address in campaign contract via the contractor.

**Comment by 0xdevcollins** [comment]
Could I take on this issue?

**Comment by mimisavage** [comment]
Can I be assigned this issue?

**Comment by manlikeHB** [comment]
Hi, Could I try solving this?
