### ISSUE TITLE
Set Storage Slot to Zero After a New Campaign is Created

### ISSUE THREAD

**Issue by mubarak23** [Token-Giver/token-giver-contracts#42]
Inside create_campaign,  Once a campaign is created, set the `withdrawal_balance` , `donations`  and `donation_count`  to zero before  CreateCampaign event was created. 

i.e 
```
 self.donation_count.write(campaign_address, 0);
 self.donations.write(campaign_address, 0);
```

**Comment by jahrulezfrancis** [comment]
I would really love to work on this issue. I’ll update the create_campaign function to initialize withdrawal_balance, donations, and donation_count to zero before triggering the CreateCampaign event. This ensures the proper setup of the campaign's state upon creation.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by wheval** [comment]
Hello, I'm Wheval a Frontend developer and Cairo Programmer.
Can I handle this issue?
I would write to the Storage to set the `donations_count` and  `donations` to a Zero (0) Value when the campaign is created.

ETA is 1 day.

**Comment by suhas-sensei** [comment]
Is it okay if I tackle this? I'll update the create_campaign function to properly initialize campaign metrics (withdrawal_balance, donations, donation_count) to zero before emitting the CreateCampaign event. 
Having worked with storage patterns in smart contracts, I'll ensure proper state initialization while maintaining event sequence integrity.

**Comment by tasneemtoolba** [comment]
Could I take a shot at this? interested in contributing in the project!!
