### ISSUE TITLE
Upgraddable Function

### ISSUE THREAD

**Issue by mubarak23** [Token-Giver/token-giver-contracts#43]
Write a function using open zeppelin that allows  us to upgrade contract base on a new class hash and also write unit test for it

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a smart contract developer specializing in StarkNet and Cairo. After completing the Cairo Basecamp, I developed and have contributed to multiple projects on OnlyDust, focusing on implementing smart contract functionality and writing comprehensive tests.

I would be happy to assist in implementing a function for upgrading contracts using OpenZeppelin and a new class hash, as well as writing unit tests to ensure its reliability. With my experience in well-tested contracts, I am confident I can tackle this task effectively. Please assign me this issue—I’m excited to contribute to this project
