### ISSUE TITLE
Implement the Lock Campaign Function

### ISSUE THREAD

**Issue by mubarak23** [Token-Giver/token-giver-contracts#46]
Base on this [frontend issue](https://github.com/Token-Giver/token-giver/issues/68), write a contract function that lock a campaign account, the function should accept lock_util as the argument ,

look at the TBA implementation [here](https://github.com/horuslabsio/TBA),

look at the [TBA workshop ](https://github.com/horuslabsio/tokenbound_v3_workshop/tree/main)for details on how the lock function was implemented 

**Acceptable Criteria**
- working function
- Test coverage

NOTE: Please specify the estimated time duration for this issue in your application.

**Comment by ekumamatthew** [comment]
Could I try solving this?

**Comment by Jagadeeshftw** [comment]
Hello @mubarak23,  

I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Here’s my proposed approach:  

### Proposed Approach  
1. Implement the `lockCampaign` function to accept `lock_util` as an argument and handle the locking logic effectively.  
2. Reference the TBA implementation and workshop to align with project standards and ensure compatibility.  
3. Add security measures to ensure only authorized accounts can lock the campaign and prevent any misuse.  
4. Write comprehensive test cases to cover all scenarios and ensure the function works as expected.  

### Estimated Time Duration  
I estimate completing this task, including implementation and testing, within **12-24 hours**.  

Looking forward to contributing!  

Best regards,  
Jagadeesh B

**Comment by mubarak23** [comment]
> Could I try solving this?

Did you read the issue description properly ?

**Comment by 1nonlypiece** [comment]
Hi @mubarak23 , I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  
ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by ekumamatthew** [comment]
Hi @mubarak23 I updated application.  I can resolve this withing 48hours

**Comment by caxtonacollins** [comment]
Is it okay if I tackle this? Will submit a good PR within 24 hours

**Comment by emarc99** [comment]
Could I try solving this? I have learnt about implementing TBA from Horus Labs. Let me do this. I will test when done.  ETA 2days

**Comment by Thibrac** [comment]
I just finished the core curriculum of the 42 school, I'm currently level 8 on node guardian, I think I can solve this issue in less than 24 🙂

**Comment by Thibrac** [comment]
I just finished the core curriculum of the 42 school, I'm currently level 8 on node guardian, I think I can solve this issue in less than 24h 🙂

**Comment by jahrulezfrancis** [comment]
I'd like to be assigned to this issue, the campaign lock function implementation. I’ll write a function that locks the campaign using a lock_util address, ensuring no double-locking occurs. I also have comprehensive test cases ready to cover all scenarios. This will also be my first contribution on this project.
Estimated time: 24 to 36 hours tops

**Comment by Birdmannn** [comment]
Hey, I'm Pascal. I'm a starknet chain cairo developer, and I can tackle this perfectly. I have looked into the frontend issue, and also comparing with horuslabs TBA implementation of this issue, the `lock` function will have the *lock_until* param that specifies the number of seconds (to be converted by the frontend assignee) for the campaign. Since this projects doesn't use components, I will add a new interface function in ICampaign, and implement it in its corresponding contract. After this, I shall carry out all possible test case scenarios concerning this function, to ensure optimal functionality without breaking any existing code. I'm in the tg, and my handle is @lemondae46. My ETA on this issue is 1 hour.

**Comment by Amarjeet325** [comment]
May I pick this up?

**Comment by ikemHood** [comment]
Hello @mubarak23, Can I contribute to this one?
i would update the Traits with the new function,
write the function that sets campaing status to locked
test the function
EDT: 24hrs

**Comment by akintewe** [comment]
Hello Good day, i would love to work on this issue as my first contribution, i have experience in Cairo, and my ETA is 12 hours

**Comment by Emmanex01** [comment]
Can I tackle this one?
I'm Emmanuel Tochukwu, a software developer. I have experience building smart contract on starknet. If given this opportunity I will deliver as fast as possible. I would appreciate if my request is given a favorable consideration.

**Comment by olisaagbafor** [comment]
Can I handle this task?

**Comment by ONEONUORA** [comment]
Could I try solving this? I am a blockchain developer.

**Comment by Supa-mega** [comment]
I’d love to work on this task.
