### ISSUE TITLE
Implement a donate function that makes use of erc20 transfer

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-contracts#5]
Right now we  handle donations(token transfer) on the frontend, we want to move this action to  the contract. Implement openzeppelin_token erc20 token component and use the transfer function to handle token transfer after donation. 

Then update `self.donations.write(campaign_address, amount);` with the amount donated.
Add a new storage map donation details

```
pub struct DonationDetails = {
  token_id
  donor_address,
  amount
}
donation_details: Map<Contract_Address, DonationDetails> //  Contract_Address Is donor_contract_address
```

Emit donation event with following fields.
```
#[derive(Drop, starknet::Event)]
pub struct DonationCreated {
    	pub campaign_id: u256,
    	pub donor_address: ContractAddress,
    	pub Amount: u256,
	pub token_id: u256,
    	pub block_timestamp: u64,
}
```

**Comment by anonfedora** [comment]
Hi I'm Eleazar, a fullstack Blockchain developer,
I will implement an interface, and a function for donation, also emit a DonationCreated event.

ETA: 48 Hours

**Comment by Emmanex01** [comment]
Could I be assigned to this?

**Comment by anihdev** [comment]
im Anih Somadina, a backend developer, ill be willing to ateend this issue, ETA 6hrs

**Comment by GideonBature** [comment]
Is it okay if I take this?

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If assigned this issue, I will send my first PR within 72 hrs. 

Thank you!

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  already  seen all code of this project i think I have good understanding  in this project .   please /assign  this issue .
Thank You

**Comment by ShantelPeters** [comment]
Could I take on this issue?
