### ISSUE TITLE
Create and test donate event

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-contracts#6]
Create a donate event that is fired off when the donate function has finished executing. Also write tests to make sure that the event is fired.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Iwueseiter** [comment]
Let me handle this issue!
Allow users to report counterfeit products by flagging suspicious items and providing supporting details to alert manufacturers and other users

**Comment by Iwueseiter** [comment]
I'd like to take this issue.
To implement this, I will initialize an event that takes the donator address, the amount donated, and the timestamp.

The event will be emitted in the donate function of the smart contract.

**Comment by Iwueseiter** [comment]
I’m interested in this one.
I'm a frontend and smart contract developer. I have a solid background in tailwindCSS, react, nextjs, javascript, typescript, cairo, rust ETC.
 


To implement this, I will initialize an event that takes the donator address, the amount donated, and the timestamp.

The event will be emitted in the donate function of the smart contract.

ETA: 6hrs.

**Comment by gidson5** [comment]
I am a seasoned Cairo developer and I will want to take this up 

ETA 2 days

**Comment by GideonBature** [comment]
May I pick this up?

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If assigned this issue, I should be able to send my first PR within 48 hrs. 

Thank you!

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  already  seen all code of this project i think I have good understanding  in this project .   please /assign  this issue .
Thank You

**Comment by ShantelPeters** [comment]
May I pick this up?

**Comment by mimiprosper** [comment]
Can I take this issue?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 2 days.
