### ISSUE TITLE
Test donate function

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-contracts#7]
Write end to end tests for the donate function.
NOTE: This issue depends on the completion of issue #5

**Comment by Akshola00** [comment]
kindly assign, i would effectively test the donate function when completed 
check for events and assert state change and make sure to add tests for panic

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Emmanex01** [comment]
I’m interested in this one.

**Comment by codeZe-us** [comment]
Could I take on this issue?
ETA: 3 hours

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by GideonBature** [comment]
Can I be assigned to this?

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If assigned this issue, I should be able to send my first PR within 48 hrs after issue #5 have been completed. 

Thank you!

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by ShantelPeters** [comment]
Could I be assigned to this?

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario, would love to work on this , my ETA is >12 Hours and ill create a draft PR in 7 hours time. Thank you for this opportunity. :)

**Comment by Michaelkingsdev** [comment]
Can I start working on this?

**Comment by No-bodyq** [comment]
Can I be assigned to this?

**Comment by mimiprosper** [comment]
Could I try solving this?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 2 days.
