### ISSUE TITLE
Implement a withdraw function

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-contracts#8]
Right now we handle withdrawal on the frontend, we want to move it to the contract side. Only a campaign owner can perform this function. Implement erc20 token transfer. Also update donations balance after transfer was successful and update withdrawal_balance storage. 
Also write tests for the function.

**Comment by anonfedora** [comment]
Hi I'm Eleazar, a fullstack Blockchain developer,
I will implement an interface, a function and a test (for withdraw) only a campaign owner can perform the withdrawal action, and Implement erc20 token transfer.

ETA: 72 Hours

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Emmanex01** [comment]
I'd like to take this issue.

**Comment by anihdev** [comment]
just concluded a cairo basecamp by GIDA acquiring an nft of participation, im very confident i can handle this. ill be happy if i get assigned

**Comment by codeZe-us** [comment]
May I pick this up?
ETA: 6 hours

**Comment by Pvsaint** [comment]
I’m interested in this one.
Hi Osho, I'm Victor Peter, a frontend and smart contract dev. May I pick this up?
I'm a first time contributor,.

How I'll handle the issue?

A withdraw method with error checking
Validation for:
Positive withdrawal amount
Sufficient account balance
Comprehensive test cases covering various scenarios

**Comment by Pvsaint** [comment]
I’m interested in this one.
Hi, I'm a frontend and smart contract dev. May I pick this up?
I'm a first time contributor,.

How I'll handle the issue?

I'll implement a withdraw method with error checking
Validation for:
Positive withdrawal amount
Sufficient account balance
Comprehensive test cases covering various scenarios
