### ISSUE TITLE
Create and test a withdraw event

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-contracts#9]
The withdraw function should emit the following event 
```
#[derive(Drop, starknet::Event)]
pub struct WithdrawalCreated {
    pub campaign_id: u256,
    pub campaign_owner_address: ContractAddress,
    pub Amount: u256,
    pub block_timestamp: u64,
}
```

write the event and also test it.

**Comment by Akshola00** [comment]
Could I work on this? I would write the event and add it to the withdrawal function, as well as include tests for it. I would love to contribute to this project.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Emmanex01** [comment]
I would love to work on this?

**Comment by Pvsaint** [comment]
Hi Osho, I'm Victor Peter, a frontend and smart contract dev. May I pick this up?

**Comment by codeZe-us** [comment]
Can I start working on this?
ETA: 5 hours

**Comment by Mystic-Nayy** [comment]
May I handle this issue?
i will Initialize the event struct with the necessary data.
Emit the event.
Perform the withdrawal logic (if not already present).

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)
